In [128]:
# How the original dataset was cleaned
import pandas as pd
medicare = pd.read_csv("medicare_2013_to_2023.csv")
medicare.columns = [col.lower() for col in medicare.columns]
medicare = medicare[medicare['bene_county_desc'] != 'Total']
medicare = medicare[medicare['month'] != 'Year']
medicare = medicare[medicare['bene_geo_lvl'] != 'State']
medicare = medicare[medicare['year'] != 2023] # since we dont have data for December 2023
medicare = medicare[medicare['bene_county_desc'] != 'Unknown']
medicare.head()

# Presence of *'s in almost all the columns
for i in medicare.columns:
    if '*' in medicare[i].value_counts():
        # print(i)
        pass

# Removing *'s
print(len(medicare))
medicare_cleaned = medicare[~medicare.isin(['*']).any(axis=1)]
medicare_cleaned.reset_index(drop=True, inplace=True)
print(len(medicare_cleaned))

# Percentage of data retained after dropping rows with *'set
print(round(len(medicare_cleaned)/ len(medicare), 2))

# Function to map state to region
def map_state_to_region(state):
    for region, states in mapping_dict.items():
        if state in states:
            return region
    return state

mapping_dict = {
    'Northeast': ['Connecticut', 'Maine', 'Massachusetts', 'New Hampshire', 'Rhode Island', 'Vermont',
                  'New Jersey', 'New York', 'Pennsylvania'],
    'Midwest': ['Illinois', 'Indiana', 'Michigan', 'Ohio', 'Wisconsin',
                'Iowa', 'Kansas', 'Minnesota', 'Missouri', 'Nebraska', 'North Dakota', 'South Dakota'],
    'South': ['Delaware', 'Florida', 'Georgia', 'Maryland', 'North Carolina', 'South Carolina', 'Virginia',
              'West Virginia', 'District of Columbia', 'Alabama', 'Kentucky', 'Mississippi', 'Tennessee', 'Arkansas', 'Louisiana',
              'Oklahoma', 'Texas'],
    'West': ['Arizona', 'Colorado', 'Idaho', 'Montana', 'Nevada', 'New Mexico', 'Utah', 'Wyoming',
             'Alaska', 'California', 'Hawaii', 'Oregon', 'Washington'],
    'Others': ['Puerto Rico', 'Virgin Islands']
}

medicare_cleaned = medicare_cleaned.copy()

# medicare_cleaned.loc[:, 'region'] = medicare_cleaned['bene_state_desc'].map(map_state_to_region)
region_column = medicare_cleaned['bene_state_desc'].map(map_state_to_region)
medicare_cleaned.insert(2, 'region', region_column)

medicare_cleaned.drop(columns=['bene_geo_lvl'], inplace=True) # Same entry for all rows 'County'

medicare_cleaned.rename(columns=lambda x: x.replace('bene_', '').replace('benes_', '').replace('_benes', '').replace('benes', ''), inplace=True)
medicare_cleaned.rename(columns=lambda x: x.replace('tot', 'total'), inplace=True)
medicare_cleaned.rename(columns=lambda x: x.replace('_mdcr', ''), inplace=True)

medicare_cleaned.rename(columns={
                                'state_abrvtn': 'state_code',
                                'state_desc': 'state',
                                'county_desc': 'county',
                                'fips_cd': 'fips_code',
                            }, inplace=True)

# # Save the cleaned dataset
medicare_cleaned.to_csv('medicare_cleaned.csv', index = False)

print(medicare_cleaned.columns)

pd.set_option('display.max_columns', None)
medicare_cleaned.head()

386820
235921
0.61
Index(['year', 'month', 'region', 'state_code', 'state', 'county', 'fips_code',
       'total', 'orgnl', 'ma_and_oth', 'aged_total', 'aged_esrd',
       'aged_no_esrd', 'dsbld_total', 'dsbld_esrd_and_esrd_only',
       'dsbld_no_esrd', 'a_b_total', 'a_b_orgnl', 'a_b_ma_and_oth',
       'prscrptn_drug_total', 'prscrptn_drug_pdp', 'prscrptn_drug_mapd',
       'prscrptn_drug_deemed_eligible_full_lis', 'prscrptn_drug_full_lis',
       'prscrptn_drug_partial_lis', 'prscrptn_drug_no_lis'],
      dtype='object')

,year,month,region,state_code,state,county,fips_code,total,orgnl,ma_and_oth,aged_total,aged_esrd,aged_no_esrd,dsbld_total,dsbld_esrd_and_esrd_only,dsbld_no_esrd,a_b_total,a_b_orgnl,a_b_ma_and_oth,prscrptn_drug_total,prscrptn_drug_pdp,prscrptn_drug_mapd,prscrptn_drug_deemed_eligible_full_lis,prscrptn_drug_full_lis,prscrptn_drug_partial_lis,prscrptn_drug_no_lis
0,2013,January,South,AL,Alabama,Autauga,01001,9210.0,6421.0,2789.0,7049.0,47.0,7002.0,2161.0,37.0,2124.0,8585.0,5796.0,2789.0,5938.0,3224.0,2714.0,1798.0,294.0,107.0,3739.0
1,2013,January,South,AL,Alabama,Baldwin,01003,40500.0,28469.0,12031.0,33905.0,132.0,33773.0,6595.0,114.0,6481.0,38058.0,26030.0,12028.0,26944.0,15418.0,11526.0,5129.0,871.0,386.0,20558.0
2,2013,January,South,AL,Alabama,Barbour,01005,5772.0,4968.0,804.0,4231.0,55.0,4176.0,1541.0,46.0,1495.0,5394.0,4590.0,804.0,4130.0,3377.0,753.0,1751.0,306.0,75.0,1998.0
3,2013,January,South,AL,Alabama,Bibb,01007,4514.0,2964.0,1550.0,3073.0,19.0,3054.0,1441.0,23.0,1418.0,4272.0,2722.0,1550.0,3314.0,1834.0,1480.0,1269.0,230.0,81.0,1734.0
4,2013,January,South,AL,Alabama,Blount,01009,11064.0,6610.0,4454.0,8569.0,34.0,8535.0,2495.0,26.0,2469.0,10379.0,5925.0,4454.0,8405.0,4105.0,4300.0,2256.0,399.0,181.0,5569.0

In [129]:
# import pandas as pd
# df = pd.read_csv("medicare_final.csv")
# df.head()